# Steering is enabled when this config is provided
num_particles: 5
start: 0.5
resampling_freq: 1
fast_steering: false
potentials:
  termini:
    _target_: bioemu.steering.TerminiDistancePotential
    target: 1.5
    flatbottom: 0.1
    slope: 3

    linear_from: .5
    order: 2
    weight: 1.0
