# Chignolin termini distance steering configuration
# This file contains only the potential definitions
# Steering parameters (num_particles, start, end, etc.) are now CLI parameters

termini:
  _target_: bioemu.steering.TerminiDistancePotential
  target: 1.5
  flatbottom: 0.1
  slope: 3.0
  linear_from: 0.5
  order: 2
  weight: 1.0
