# Configuration for disulfide bridge steering
# This includes physical potentials and the DisulfideBridgePotential

# chainbreak:
#   _target_: bioemu.steering.ChainBreakPotential
#   flatbottom: 0.
#   slope: 5.
#   order: 2
#   linear_from: 10
#   weight: 1.0

# chainclash:
#   _target_: bioemu.steering.ChainClashPotential
#   flatbottom: 0.
#   dist: 4.1
#   slope: 5.
#   weight: 1.0

disulfide:
  _target_: bioemu.steering.DisulfideBridgePotential
  flatbottom: 0.01
  slope: 100.0
  weight: 1.0
  # specified_pairs will be provided via CLI parameter --disulfidebridges
